# Generated by Django 5.2.8 on 2025-11-19 09:44

import borrowing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Borrowing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("OP", "Open"), ("CL", "Closed")],
                        default="OP",
                        max_length=2,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BorrowingItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                ("borrow_date", models.DateField(auto_now_add=True)),
                (
                    "expected_return_date",
                    models.DateField(default=borrowing.models.return_date),
                ),
                ("actual_return_date",
                 models.DateField(
                     blank=True, null=True
                 )
                 ),
            ],
        ),
    ]
