# Generated by Django 5.2.8 on 2025-11-19 09:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("borrowing", "0001_initial"),
        ("library", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="borrowing",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="borrowingitem",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="library.book"
            ),
        ),
        migrations.AddField(
            model_name="borrowingitem",
            name="borrowing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="borrowing.borrowing",
            ),
        ),
        migrations.AddField(
            model_name="borrowing",
            name="books",
            field=models.ManyToManyField(
                related_name="borrowings",
                through="borrowing.BorrowingItem",
                to="library.book",
            ),
        ),
        migrations.AddConstraint(
            model_name="borrowingitem",
            constraint=models.UniqueConstraint(
                fields=("borrowing", "book"), name="unique_borrowing_item"
            ),
        ),
        migrations.AddConstraint(
            model_name="borrowingitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)),
                name="borrowingitem_quantity_gt_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="borrowingitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("expected_return_date__gte", models.F("borrow_date"))
                ),
                name="borrowingitem_expected_gte_borrow",
            ),
        ),
        migrations.AddConstraint(
            model_name="borrowingitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("actual_return_date__isnull", True),
                    ("actual_return_date__gte", models.F("borrow_date")),
                    _connector="OR",
                ),
                name="borrowingitem_actual_gte_borrow_or_null",
            ),
        ),
    ]
